name: TodoApp
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  flutter_slidable: ^4.0.0
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.4.6
  fluentui_system_icons: ^1.1.273
  table_calendar: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - images/

flutter_native_splash:
  android: true
  ios: true
  web: false
  
  background_image: "images/background.png"
  image: "images/android_logo.png"
  branding: "images/branding.png"

  android_12:
    image: "images/android_logo.png"
    icon_background_color: "#FFFFFF"
    branding: "images/branding.png"